tower:
  trustedEmails:
    - '*@seqera.io'
    - '*@salenda.es'
  serverUrl: http://localhost:4200
---
micronaut:
  server:
    cors:
      enabled: true
  security:
    session:
      enabled: true
      loginSuccessTargetUrl: "${TOWER_SERVER_URL:`http://localhost:4200`}/access?success=true"
      loginFailureTargetUrl: "${TOWER_SERVER_URL:`http://localhost:4200`}/access?success=false"
      logoutTargetUrl: "${TOWER_SERVER_URL:`http://localhost:4200`}/logout"

---
dataSource:
  pooled: true
  dbCreate: "${DB_CREATE:update}"
  url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/tower"
  driverClassName: "${DB_DRIVER:com.mysql.cj.jdbc.Driver}"
  username: "${DB_USER:tower}"
  password: "${DB_PASSWORD:tower}"
hibernate:
  dialect: "${DB_DIALECT:org.hibernate.dialect.MySQL55Dialect}"
---
mail:
  from: noreply@salenda.net
  to: qa@salenda.es
  smtp:
    host: smtp.salenda.es
    port: 25
    auth: false
    user:
    password:
    starttls:
      enable: false
      required: false
---
auth:
  mail:
    duration: 1d
